## Step 1: Create 3 Random Matrices

In [1]:
import numpy as np

# no fixed seed so different each run
rang = np.random.default_rng()
matrices = [rang.integers(-10, 11, size=(3,3)) for _ in range(3)]

## Step 2 & 3: Compute Inverse of Each Matrix & Check by Obtaining Identity Matrix

In [3]:
inverses = []

for i, A in enumerate(matrices, start=1):
    print(f"\nMatrix {i}:\n{A}")
    try:
        A_inv = np.linalg.inv(A)
        inverses.append(A_inv)
        print("Inverse:\n", A_inv)

        print("Identity Matrix:\n", np.round(A @ A_inv, 6))
    except np.linalg.LinAlgError:
        inverses.append(None)
        print("Singular matrix: no inverse.")



Matrix 1:
[[ -8   5  10]
 [  2 -10  -8]
 [ -3   7  -3]]
Inverse:
 [[-0.12320917 -0.1217765  -0.08595989]
 [-0.04297994 -0.0773639   0.06303725]
 [ 0.02292264 -0.05873926 -0.10028653]]
Identity Matrix:
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]

Matrix 2:
[[-8 -1 -2]
 [-2 -3 -9]
 [-9  2  7]]
Inverse:
 [[  0.33333333  -0.33333333  -0.33333333]
 [-10.55555556   8.22222222   7.55555556]
 [  3.44444444  -2.77777778  -2.44444444]]
Identity Matrix:
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]

Matrix 3:
[[-10   7   7]
 [ -7   9  -8]
 [ -9  -9  -3]]
Inverse:
 [[-0.04203822 -0.01783439 -0.05053079]
 [ 0.02165605  0.03949045 -0.05477707]
 [ 0.0611465  -0.06496815 -0.01740977]]
Identity Matrix:
 [[ 1.  0. -0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
